============================= test session starts ==============================
platform linux -- Python 3.10.13, pytest-8.3.3, pluggy-1.5.0
rootdir: /app
plugins: asyncio-0.24.0, anyio-4.2.0
asyncio: mode=strict, default_loop_scope=None

----------------------------- live log collection ------------------------------
INFO     numexpr.utils:utils.py:160 NumExpr defaulting to 8 threads.
collected 4 items / 1 error

==================================== ERRORS ====================================
______________________ ERROR collecting tests/test_api.py ______________________
/opt/conda/envs/clean_env/lib/python3.10/site-packages/pytest_asyncio/plugin.py:667: in _patched_collect
    module = collector.obj
/opt/conda/envs/clean_env/lib/python3.10/site-packages/_pytest/python.py:284: in obj
    self._obj = obj = self._getobj()
/opt/conda/envs/clean_env/lib/python3.10/site-packages/_pytest/python.py:546: in _getobj
    return importtestmodule(self.path, self.config)
/opt/conda/envs/clean_env/lib/python3.10/site-packages/_pytest/python.py:493: in importtestmodule
    mod = import_path(
/opt/conda/envs/clean_env/lib/python3.10/site-packages/_pytest/pathlib.py:582: in import_path
    importlib.import_module(module_name)
/opt/conda/envs/clean_env/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
<frozen importlib._bootstrap>:1050: in _gcd_import
    ???
<frozen importlib._bootstrap>:1027: in _find_and_load
    ???
<frozen importlib._bootstrap>:1006: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:688: in _load_unlocked
    ???
/opt/conda/envs/clean_env/lib/python3.10/site-packages/_pytest/assertion/rewrite.py:184: in exec_module
    exec(co, module.__dict__)
/Users/bennyschellinger/Desktop/DataScience/MLE_DataScientest/04_Projekt/MLOps/AUG24-BMLOPS-INT-LFB/tests/test_api.py:3: in <module>
    ???
main.py:4: in <module>
    from app.routes import prediction, evaluation, database, token_generator
routes/prediction.py:7: in <module>
    model, pca = load_model_and_pca()
utils.py:32: in load_model_and_pca
    with open(pca_path, 'rb') as pca_file:
E   FileNotFoundError: [Errno 2] No such file or directory: 'model/pca.pkl'
=============================== warnings summary ===============================
../opt/conda/envs/clean_env/lib/python3.10/site-packages/sklearn/base.py:376
  /opt/conda/envs/clean_env/lib/python3.10/site-packages/sklearn/base.py:376: InconsistentVersionWarning: Trying to unpickle estimator DecisionTreeClassifier from version 1.4.2 when using version 1.5.1. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
  https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
    warnings.warn(

../opt/conda/envs/clean_env/lib/python3.10/site-packages/sklearn/base.py:376
  /opt/conda/envs/clean_env/lib/python3.10/site-packages/sklearn/base.py:376: InconsistentVersionWarning: Trying to unpickle estimator RandomForestClassifier from version 1.4.2 when using version 1.5.1. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
  https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
    warnings.warn(

../opt/conda/envs/clean_env/lib/python3.10/site-packages/sklearn/base.py:376
  /opt/conda/envs/clean_env/lib/python3.10/site-packages/sklearn/base.py:376: InconsistentVersionWarning: Trying to unpickle estimator LogisticRegression from version 1.4.2 when using version 1.5.1. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
  https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
    warnings.warn(

../opt/conda/envs/clean_env/lib/python3.10/site-packages/sklearn/base.py:376
  /opt/conda/envs/clean_env/lib/python3.10/site-packages/sklearn/base.py:376: InconsistentVersionWarning: Trying to unpickle estimator LabelEncoder from version 1.4.2 when using version 1.5.1. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
  https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
    warnings.warn(

../opt/conda/envs/clean_env/lib/python3.10/site-packages/xgboost/core.py:158
  /opt/conda/envs/clean_env/lib/python3.10/site-packages/xgboost/core.py:158: UserWarning: [01:30:49] WARNING: /croot/xgboost-split_1724073753743/work/src/collective/../data/../common/error_msg.h:80: If you are loading a serialized model (like pickle in Python, RDS in R) or
  configuration generated by an older version of XGBoost, please export the model by calling
  `Booster.save_model` from that version first, then load it back in current version. See:
  
      https://xgboost.readthedocs.io/en/stable/tutorials/saving_model.html
  
  for more details about differences between saving model and serializing.
  
    warnings.warn(smsg, UserWarning)

../opt/conda/envs/clean_env/lib/python3.10/site-packages/sklearn/base.py:376
  /opt/conda/envs/clean_env/lib/python3.10/site-packages/sklearn/base.py:376: InconsistentVersionWarning: Trying to unpickle estimator VotingClassifier from version 1.4.2 when using version 1.5.1. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
  https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
    warnings.warn(

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=========================== short test summary info ============================
ERROR tests/test_api.py - FileNotFoundError: [Errno 2] No such file or direct...
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
========================= 6 warnings, 1 error in 0.95s =========================
