[2024-09-27T13:04:35.650+0200] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/isi/Desktop/LFB/AUG24-BMLOPS-INT-LFB/airflow/dags/predict_model_dag.py", line 61, in fetch_data_from_mongodb
    data = pd.DataFrame(list(collection.find()))
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/pymongo/synchronous/cursor.py", line 1281, in __next__
    return self.next()
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/pymongo/synchronous/cursor.py", line 1257, in next
    if len(self._data) or self._refresh():
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/pymongo/synchronous/cursor.py", line 1205, in _refresh
    self._send_message(q)
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/pymongo/synchronous/cursor.py", line 1100, in _send_message
    response = client._run_operation(
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/pymongo/_csot.py", line 120, in csot_wrapper
    return func(self, *args, **kwargs)
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/pymongo/synchronous/mongo_client.py", line 1754, in _run_operation
    return self._retryable_read(
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/pymongo/synchronous/mongo_client.py", line 1863, in _retryable_read
    return self._retry_internal(
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/pymongo/_csot.py", line 120, in csot_wrapper
    return func(self, *args, **kwargs)
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/pymongo/synchronous/mongo_client.py", line 1830, in _retry_internal
    ).run()
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/pymongo/synchronous/mongo_client.py", line 2554, in run
    return self._read() if self._is_read else self._write()
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/pymongo/synchronous/mongo_client.py", line 2689, in _read
    self._server = self._get_server()
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/pymongo/synchronous/mongo_client.py", line 2645, in _get_server
    return self._client._select_server(
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/pymongo/synchronous/mongo_client.py", line 1649, in _select_server
    server = topology.select_server(
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/pymongo/synchronous/topology.py", line 397, in select_server
    server = self._select_server(
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/pymongo/synchronous/topology.py", line 375, in _select_server
    servers = self.select_servers(
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/pymongo/synchronous/topology.py", line 282, in select_servers
    server_descriptions = self._select_servers_loop(
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/pymongo/synchronous/topology.py", line 332, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: mongo:27017: [Errno -3] Temporary failure in name resolution (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 66f6912581ff048a2daf9e3c, topology_type: Unknown, servers: [<ServerDescription ('mongo', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('mongo:27017: [Errno -3] Temporary failure in name resolution (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>
[2024-09-27T13:04:35.703+0200] {standard_task_runner.py:124} ERROR - Failed to execute job 8 for task fetch_data_task (mongo:27017: [Errno -3] Temporary failure in name resolution (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 66f6912581ff048a2daf9e3c, topology_type: Unknown, servers: [<ServerDescription ('mongo', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('mongo:27017: [Errno -3] Temporary failure in name resolution (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>; 61471)
Traceback (most recent call last):
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/isi/Desktop/LFB/AUG24-BMLOPS-INT-LFB/airflow/dags/predict_model_dag.py", line 61, in fetch_data_from_mongodb
    data = pd.DataFrame(list(collection.find()))
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/pymongo/synchronous/cursor.py", line 1281, in __next__
    return self.next()
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/pymongo/synchronous/cursor.py", line 1257, in next
    if len(self._data) or self._refresh():
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/pymongo/synchronous/cursor.py", line 1205, in _refresh
    self._send_message(q)
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/pymongo/synchronous/cursor.py", line 1100, in _send_message
    response = client._run_operation(
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/pymongo/_csot.py", line 120, in csot_wrapper
    return func(self, *args, **kwargs)
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/pymongo/synchronous/mongo_client.py", line 1754, in _run_operation
    return self._retryable_read(
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/pymongo/synchronous/mongo_client.py", line 1863, in _retryable_read
    return self._retry_internal(
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/pymongo/_csot.py", line 120, in csot_wrapper
    return func(self, *args, **kwargs)
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/pymongo/synchronous/mongo_client.py", line 1830, in _retry_internal
    ).run()
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/pymongo/synchronous/mongo_client.py", line 2554, in run
    return self._read() if self._is_read else self._write()
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/pymongo/synchronous/mongo_client.py", line 2689, in _read
    self._server = self._get_server()
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/pymongo/synchronous/mongo_client.py", line 2645, in _get_server
    return self._client._select_server(
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/pymongo/synchronous/mongo_client.py", line 1649, in _select_server
    server = topology.select_server(
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/pymongo/synchronous/topology.py", line 397, in select_server
    server = self._select_server(
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/pymongo/synchronous/topology.py", line 375, in _select_server
    servers = self.select_servers(
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/pymongo/synchronous/topology.py", line 282, in select_servers
    server_descriptions = self._select_servers_loop(
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/pymongo/synchronous/topology.py", line 332, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: mongo:27017: [Errno -3] Temporary failure in name resolution (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 66f6912581ff048a2daf9e3c, topology_type: Unknown, servers: [<ServerDescription ('mongo', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('mongo:27017: [Errno -3] Temporary failure in name resolution (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>
[2024-09-27T15:39:25.415+0200] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/isi/Desktop/LFB/AUG24-BMLOPS-INT-LFB/airflow/dags/predict_model_dag.py", line 56, in fetch_data_from_mongodb
    mongo_hook = MongoHook(conn_id='mongo_conn')  # Use conn_id for Airflow connection
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/airflow/providers/mongo/hooks/mongo.py", line 132, in __init__
    self._validate_connection(conn)
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/airflow/providers/mongo/hooks/mongo.py", line 168, in _validate_connection
    raise AirflowConfigException(
airflow.exceptions.AirflowConfigException: conn_type 'mongodb' not allowed for MongoHook; conn_type must be 'mongo'
[2024-09-27T15:39:25.432+0200] {standard_task_runner.py:124} ERROR - Failed to execute job 42 for task fetch_data_task (conn_type 'mongodb' not allowed for MongoHook; conn_type must be 'mongo'; 129347)
Traceback (most recent call last):
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/isi/Desktop/LFB/AUG24-BMLOPS-INT-LFB/airflow/dags/predict_model_dag.py", line 56, in fetch_data_from_mongodb
    mongo_hook = MongoHook(conn_id='mongo_conn')  # Use conn_id for Airflow connection
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/airflow/providers/mongo/hooks/mongo.py", line 132, in __init__
    self._validate_connection(conn)
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/airflow/providers/mongo/hooks/mongo.py", line 168, in _validate_connection
    raise AirflowConfigException(
airflow.exceptions.AirflowConfigException: conn_type 'mongodb' not allowed for MongoHook; conn_type must be 'mongo'
[2024-09-27T16:04:59.303+0200] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/isi/Desktop/LFB/AUG24-BMLOPS-INT-LFB/airflow/dags/predict_model_dag.py", line 56, in fetch_data_from_mongodb
    mongo_hook = MongoHook(conn_id='mongo_conn')
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/airflow/providers/mongo/hooks/mongo.py", line 132, in __init__
    self._validate_connection(conn)
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/airflow/providers/mongo/hooks/mongo.py", line 168, in _validate_connection
    raise AirflowConfigException(
airflow.exceptions.AirflowConfigException: conn_type 'mongodb' not allowed for MongoHook; conn_type must be 'mongo'
[2024-09-27T16:04:59.322+0200] {standard_task_runner.py:124} ERROR - Failed to execute job 56 for task fetch_data_task (conn_type 'mongodb' not allowed for MongoHook; conn_type must be 'mongo'; 141866)
Traceback (most recent call last):
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/isi/Desktop/LFB/AUG24-BMLOPS-INT-LFB/airflow/dags/predict_model_dag.py", line 56, in fetch_data_from_mongodb
    mongo_hook = MongoHook(conn_id='mongo_conn')
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/airflow/providers/mongo/hooks/mongo.py", line 132, in __init__
    self._validate_connection(conn)
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/airflow/providers/mongo/hooks/mongo.py", line 168, in _validate_connection
    raise AirflowConfigException(
airflow.exceptions.AirflowConfigException: conn_type 'mongodb' not allowed for MongoHook; conn_type must be 'mongo'
