[2024-09-27T14:56:15.208+0200] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/isi/Desktop/LFB/AUG24-BMLOPS-INT-LFB/airflow/dags/predict_model_dag.py", line 56, in fetch_data_from_mongodb
    mongo_hook = MongoHook(conn_id='mongo_conn')  # Use conn_id for Airflow connection
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/airflow/providers/mongo/hooks/mongo.py", line 132, in __init__
    self._validate_connection(conn)
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/airflow/providers/mongo/hooks/mongo.py", line 168, in _validate_connection
    raise AirflowConfigException(
airflow.exceptions.AirflowConfigException: conn_type 'mongodb' not allowed for MongoHook; conn_type must be 'mongo'
[2024-09-27T14:56:15.225+0200] {standard_task_runner.py:124} ERROR - Failed to execute job 37 for task fetch_data_task (conn_type 'mongodb' not allowed for MongoHook; conn_type must be 'mongo'; 106599)
Traceback (most recent call last):
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/isi/Desktop/LFB/AUG24-BMLOPS-INT-LFB/airflow/dags/predict_model_dag.py", line 56, in fetch_data_from_mongodb
    mongo_hook = MongoHook(conn_id='mongo_conn')  # Use conn_id for Airflow connection
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/airflow/providers/mongo/hooks/mongo.py", line 132, in __init__
    self._validate_connection(conn)
  File "/home/isi/miniconda3/envs/clean_env/lib/python3.10/site-packages/airflow/providers/mongo/hooks/mongo.py", line 168, in _validate_connection
    raise AirflowConfigException(
airflow.exceptions.AirflowConfigException: conn_type 'mongodb' not allowed for MongoHook; conn_type must be 'mongo'
